### ISSUE TITLE
Dialog showing mappings between ontologies displays doubled

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#103]
Steps to reproduce:

1. Navigate to any ontology in BioPortal with mappings, e.g., [SNOMEDCT](https://bioportal.bioontology.org/ontologies/SNOMEDCT).
2. Click the Mappings tab.
3. Click on any ontology in the table.

Notice that the resulting dialog shows the table of mappings between the two ontologies twice with duplicate data:
![Screenshot 2019-10-02 17 30 36](https://user-images.githubusercontent.com/1696923/66090957-6c56c300-e53a-11e9-8550-ec98debd40f0.png)

**Comment by graybeal** [comment]
Originally reported (sort of) as bioportal-project/69
