### ISSUE TITLE
replace URL pattern '/visualize/virtual' with '/ontologies' for links displayed in the ontology mappings view. 

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#106]
ontology mappings view has outdated URL pattern '/visualize/virtual' which is redirecting to /ontologies/.   That URL pattern should be changed to /ontologies in order to reduce unnesesary redirections. 

I am referring to links that are displayed in the pop-up window when clicking on one of the mapped ontology in the ontology mappings view.

**Comment by jvendetti** [comment]
Steps to reproduce:

1. Navigate to the top-level Mappings tab in BioPortal.
2. Select any ontology from the drop down box.
3. In the resulting table, click any ontology.
4. In the resulting dialog, click any class name in either column.

Notice the 301 redirect, e.g.:

```
Started GET "/visualize/virtual/BRO?conceptid=http%3A%2F%2Fbioontology.org%2Fontologies%2FBiomedicalResourceOntology.owl%23Report" for ::1 at 2019-11-20 14:28:59 -0800
Processing by ConceptsController#virtual as HTML
  Parameters: {"conceptid"=>"http://bioontology.org/ontologies/BiomedicalResourceOntology.owl#Report", "ontology"=>"BRO"}
Redirected to http://localhost:3000/ontologies/BRO?p=classes&conceptid=http%3A%2F%2Fbioontology.org%2Fontologies%2FBiomedicalResourceOntology.owl%23Report
Completed 301 Moved Permanently in 6ms (ActiveRecord: 0.0ms)
```

These redirects were done intentionally when the system was being transitioned from the old API to the new. However, the old API was [retired at the end of 2013](https://www.bioontology.org/wiki/BioPortal_4_Release_Notes#BioPortal_Release_4.0_.28September_2013.29), and these redirects are undoubtedly no longer necessary.
