### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#116]
GitHub is reporting a moderate level security vulnerability with the version we're using (4.1.0).

**Comment by jvendetti** [comment]
The desire to upgrade to Bootstrap 5 is becoming more pressing. We want to use some of the newer components for the ontology change request functionality that's funded under the BioPortal U24 grant.

I'm working on this periodically as time allows in [this branch](https://github.com/ncbo/bioportal_web_ui/tree/bootstrap-5).

**Comment by syphax-bouazzouni** [comment]
Hi @jvendetti, great news to hear that you will work on that. 

A small suggestion (if I may) is that this type of long-running branch (work) is to create a parallel PR, which will make it easier to follow up, see changes, and review. Giving a global overview of the work done to make it easier to understand and merge for external collaborators. (in our side I already created this https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/275 to follow it)

**Comment by jvendetti** [comment]
Hi @syphax-bouazzouni. Sure, no problem - I created a draft pull request. When I have a moment, I'll augment the description with a task list of the remaining display and/or functional issues that I still need to address.
