### ISSUE TITLE
Upgrade to Ruby 2.6.6

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#142]
Make any necessary modifications to go from Ruby 2.5 to Ruby 2.6.6:

- Test locally against 2.6.6
- Deploy any necessary modifications to the staging environment (upgraded June 23rd to Ruby 2.6)
- Assuming staging looks good, deploy to production

**Comment by jvendetti** [comment]
@alexskr - do I understand correctly after today's developer meeting that the UI boxes in production are on Ruby 2.6? If so, I'll close this issue.

**Comment by alexskr** [comment]
yes, prod, stage, and appliance systems are all running ruby 2.6.6
