### ISSUE TITLE
Downloading ontology submissions fails in Chrome with Mixed Content error

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#161]
Steps to reproduce:

1. Launch the Chrome browser
2. Navigate to any ontology summary page in BioPortal, e.g.: https://bioportal.bioontology.org/ontologies/DRON
3. In the Submissions table, click on any of the OWL files in the Downloads column

Open the Web Console pane in developer tools and notice the resulting mixed content error:

```Mixed Content: The site at 'https://bioportal.bioontology.org/' was loaded over a secure connection, but the file at 'http://data.bioontology.org/ontologies/DRON/submissions/12/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.```

Possibly caused by the recent "bioportal UI http -> https redirect is enabled in prod" on January 27th. Current workaround for end users is to download submissions using either Firefox or Safari.

**Comment by jvendetti** [comment]
@alexskr - I noticed that this bug isn't reproducible in our staging environment because submission download links are generated with HTTPS protocol, e.g.:

```
<a href="https://stagedata.bioontology.org/ontologies/DRON/submissions/12/download?apikey=" rel="nofollow">OWL</a>
```

... vs. our production environment where the download links are still using HTTP:

```
<a href="http://data.bioontology.org/ontologies/DRON/submissions/12/download?apikey=" rel="nofollow">OWL</a>
```

I also noticed some differences between the configuration files for our staging and production environments, namely the [$REST_URL variable](https://github.com/ncbo/bioportal_config/blob/e406c98850b37ee8b7ce5425357c88b67cff6498/bioportal_web_ui/config/bioportal_config_staging.rb#L32) is using HTTPS in staging, but not in production. Back in September of 2019 it looks like you modified the protocols to use HTTPS in staging in [this commit](https://github.com/ncbo/bioportal_config/commit/19574f120d2e93007b59d1b5fc52583ad399acf8). Do we need to make the same modifications in production? The [code](https://github.com/ncbo/bioportal_web_ui/blob/b33ca410d8922beb1c51ccb373262e9563d03166/app/helpers/ontologies_helper.rb#L32) that generates the download links has remained unchanged for a while now.

**Comment by alexskr** [comment]
I updated UI and API configs to get download links to work properly.

**Comment by jvendetti** [comment]
See the following commits for fixes:

https://github.com/ncbo/bioportal_config/commit/b9cc915167adb658e69f6249b68704c625b5887f
https://github.com/ncbo/bioportal_config/commit/ab07b25f924770c88af2110528b1b5b65bed2ea5
