### ISSUE TITLE
Broken link on the class visualization page

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal_web_ui#18]
The link "Open concept homepage in tab" is broken. It points to:
http://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C22187

The last part (conceptid=<>) should be URL-encoded but it isn't.

To reproduce:

1. http://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C25379#visualization
2. Right click on the term and click on "Open concept homepage in tab"

**Comment by jvendetti** [comment]
@graybeal and @mdorf:  This is an issue in the BioMixer visualization plug-in code (developed at the University of Victoria).  I created a new issue in our forked version of BioMixer: ncbo/biomixer#1.
