### ISSUE TITLE
deprecate LEGACY_REST_URL variable

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#211]
According to the sample config file `LEGACY_REST_URL` is 'Legacy REST core service address (BioPortal v3.x and lower)'
BioPortal v3.x rest service was deprecated a while ago but this variable still in use:
https://github.com/ncbo/bioportal_web_ui/blob/b33ca410d8922beb1c51ccb373262e9563d03166/app/controllers/ajax_proxy_controller.rb#L28
https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb#L30

**Comment by syphax-bouazzouni** [comment]
In addition, there are 3 more places where it's used, see the screenshot below. 

![image](https://user-images.githubusercontent.com/29259906/188771065-26ffcff8-17bf-470c-85c1-684c65f45b04.png)

**Comment by alexskr** [comment]
flexviz is another deprecated adobe flash based visualization which needs to be purged as well

**Comment by alexskr** [comment]
can we remove these files?

https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/views/concepts/_software.html.erb
https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/views/concepts/_images.rhtmlold
https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/views/concepts/_flexviz.html.erb
https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/views/concepts/_images.html.erb

**Comment by syphax-bouazzouni** [comment]
in addition (two),  the `LEGACY_REST_URL` is called in [jsonp](https://github.com/ncbo/bioportal_web_ui/blob/b33ca410d8922beb1c51ccb373262e9563d03166/app/controllers/ajax_proxy_controller.rb#L17) and [remote](https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb#L26) methods, where they themselves are not used anywhere.

### jsonp
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/29259906/188790119-448dc131-9ddd-4b26-9125-cf159a8c3698.png">

### remote 
remote is called inside 
https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb#L14

But will never be called because the add function is called nowhere in the code with `request` argument 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/29259906/188790492-f28f2502-86bc-4728-885b-48ab7fb09b8b.png">

### my (personnel) conclusion 

- we can remove [jsonp](https://github.com/ncbo/bioportal_web_ui/blob/b33ca410d8922beb1c51ccb373262e9563d03166/app/controllers/ajax_proxy_controller.rb#L17) and its [route](https://github.com/ncbo/bioportal_web_ui/blob/b33ca410d8922beb1c51ccb373262e9563d03166/app/controllers/ajax_proxy_controller.rb#L17)
- we can remove [remote](https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb#L26) and its call in add
- we can also remove `$REMOTE_LOGGING` in the [sample config file](https://github.com/ncbo/bioportal_web_ui/blob/master/config/bioportal_config_env.rb.sample#L115), because it was only used in [remote](https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb#L26)

**Comment by syphax-bouazzouni** [comment]
Finally, I have some time ago a list of the unused view (that you can see below), stay to list all the related unused code to these views.

- home/account.html.erb
- home/user.html.erb
- ontologies/_private_ontology.html.erb
- ontologies/_views.html.haml
- ontologies/_details.html.haml
- ontologies/_licensed_ontology.html.erb
- notifier/error.html.erb
- notifier/signup.html.erb
- notifier/lost_password.html.erb
- notifier/endlessloop.html.erb
- admin/index.html.erb.old
- admin/_memcache_stats.html.erb
- shared/_not_browsable.html.erb
- search/_concepts.html.erb
- search/search.html.erb
- search/_results.html.erb
- search/_concept_preview.html.erb
- notes/_list.html.haml
- layouts/minimal.html.erb
- layouts/_ontology.html.haml
- layouts/angular.html.erb
- layouts/_head_common.html.erb
- layouts/partial.html.erb
- concepts/_images.html.erb
- concepts/_images.rhtmlold
- concepts/_flexviz.html.erb
- concepts/_software.html.erb
- mappings/upload.html.erb
- application/_footer_appliance.html.haml
- margin_notes/_update.html.erb
- margin_notes/_proposal.html.erb
- margin_notes/_show.html.erb
- reviews/index.html.erb
- reviews/_review.html.haml
- reviews/edit.html.erb
- reviews/show.html.erb
- reviews/new.html.haml

**Comment by alexskr** [comment]
If i understand this correctly this log.rb function was previously used for UI to log events to now obsolete/non-existing v3 rest API.  think this can be safely removed? https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb

**Comment by jvendetti** [comment]
I wasn't able to look at all 37 of the view templates that are listed as unused, but at first glance there are at least a few that are still employed by BioPortal.

### layouts/angular.html.erb

This is the layout used by the ontology Browse page:

```
Started GET "/ontologies" for 127.0.0.1 at 2022-09-07 10:52:24 -0700
Processing by OntologiesController#index as HTML
  Rendering ontologies/browse.html.erb within layouts/angular
```

### layouts/_ontology.html.haml

This layout is referenced inside of the `virtual_show` method in the notes controller:

https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/controllers/notes_controller.rb#L35

The method can be triggered by navigating to the top-level Notes tab for any ontology with notes, then clicking on any note subject:

```
Started GET "/ontologies/BRO/notes/https%3A%2F%2Fdata.bioontology.org%2Fnotes%2Fa5809cba-e4dd-4553-9b24-c010f9d27b50" for 127.0.0.1 at 2022-09-07 14:19:57 -0700
Processing by NotesController#virtual_show as */*
  Parameters: {"ontology"=>"BRO", "noteid"=>"https://data.bioontology.org/notes/a5809cba-e4dd-4553-9b24-c010f9d27b50"}
  Rendered notes/_thread.html.haml (Duration: 1610.9ms | Allocations: 3108739)
Completed 200 OK in 15722ms (Views: 1611.3ms | ActiveRecord: 0.0ms | Allocations: 3473884)
```

... though it wasn't immediately clear what would trigger the `elseif` and `else` clauses inside this method that reference the ontology layout partial.

#### application/_footer_appliance.html.haml

Used to render a different footer when running the application in appliance mode:

https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/views/layouts/appliance.html.haml#L35

#### notes/_list.html.haml

Used to render the notes associated with a particular class:

```
Started GET "/ajax_concepts/BRO/?conceptid=http%3A%2F%2Fbioontology.org%2Fontologies%2FResearchArea.owl%23Area_of_Research&callback=load" for 127.0.0.1 at 2022-09-07 14:00:14 -0700
Processing by ConceptsController#show as */*
  Parameters: {"conceptid"=>"http://bioontology.org/ontologies/ResearchArea.owl#Area_of_Research", "callback"=>"load", "ontology"=>"BRO"}
  Ontology Load (0.3ms)  SELECT `ontologies`.* FROM `ontologies` WHERE `ontologies`.`acronym` = 'BRO' LIMIT 1
  ↳ app/helpers/application_helper.rb:367:in `ontolobridge_instructions_template'
  Rendered concepts/_biomixer.html.erb (Duration: 0.1ms | Allocations: 42)
  Rendered concepts/_details.html.haml (Duration: 775.1ms | Allocations: 7617)
  Rendered notes/_list.html.haml (Duration: 6957.3ms | Allocations: 363722)
```

**Comment by syphax-bouazzouni** [comment]
> ### layouts/angular.html.erb
> This is the layout used by the ontology Browse page:
> 
> ```
> Started GET "/ontologies" for 127.0.0.1 at 2022-09-07 10:52:24 -0700
> Processing by OntologiesController#index as HTML
>   Rendering ontologies/browse.html.erb within layouts/angular
> ```

Yeah, for the `angular` layout indeed it is used, I don't remember why I listed it in my notes. Maybe just to remember to remove angular-js and update the browse page.  


> ### layouts/_ontology.html.haml
> This layout is referenced inside of the `virtual_show` method in the notes controller:
> 
> https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/controllers/notes_controller.rb#L35
> 
> The method can be triggered by navigating to the top-level Notes tab for any ontology with notes, then clicking on any note subject:
> 
> ```
> Started GET "/ontologies/BRO/notes/https%3A%2F%2Fdata.bioontology.org%2Fnotes%2Fa5809cba-e4dd-4553-9b24-c010f9d27b50" for 127.0.0.1 at 2022-09-07 14:19:57 -0700
> Processing by NotesController#virtual_show as */*
>   Parameters: {"ontology"=>"BRO", "noteid"=>"https://data.bioontology.org/notes/a5809cba-e4dd-4553-9b24-c010f9d27b50"}
>   Rendered notes/_thread.html.haml (Duration: 1610.9ms | Allocations: 3108739)
> Completed 200 OK in 15722ms (Views: 1611.3ms | ActiveRecord: 0.0ms | Allocations: 3473884)
> ```
> 
> ... though it wasn't immediately clear what would trigger the `elseif` and `else` clauses inside this method that reference the ontology layout partial.
> 

Yes, but I think that the `elseif` and `else` clauses inside will never be fulfilled (not 100% sure) 

> #### application/_footer_appliance.html.haml
> Used to render a different footer when running the application in appliance mode:
> 
> https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/app/views/layouts/appliance.html.haml#L35
> 

Ah yes, i found that its only our local code that does no more is it.

> #### notes/_list.html.haml
> Used to render the notes associated with a particular class:
> 
> ```
> Started GET "/ajax_concepts/BRO/?conceptid=http%3A%2F%2Fbioontology.org%2Fontologies%2FResearchArea.owl%23Area_of_Research&callback=load" for 127.0.0.1 at 2022-09-07 14:00:14 -0700
> Processing by ConceptsController#show as */*
>   Parameters: {"conceptid"=>"http://bioontology.org/ontologies/ResearchArea.owl#Area_of_Research", "callback"=>"load", "ontology"=>"BRO"}
>   Ontology Load (0.3ms)  SELECT `ontologies`.* FROM `ontologies` WHERE `ontologies`.`acronym` = 'BRO' LIMIT 1
>   ↳ app/helpers/application_helper.rb:367:in `ontolobridge_instructions_template'
>   Rendered concepts/_biomixer.html.erb (Duration: 0.1ms | Allocations: 42)
>   Rendered concepts/_details.html.haml (Duration: 775.1ms | Allocations: 7617)
>   Rendered notes/_list.html.haml (Duration: 6957.3ms | Allocations: 363722)
> ```

Indeed, 


I updated the list with your remarks, thanks @jvendetti.
