### ISSUE TITLE
remove remote logging

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#213]
Remove remote deprecated logging functionality. 

[log.rb](https://github.com/ncbo/bioportal_web_ui/blob/6f1fb336eb27e57c444750c6c187bf23cc60a3b8/lib/log.rb) includes remote logging functionality if REMOTE_LOGGING is set.  It was previously used for UI to log events to obsolete/non-existing v3 rest API.

**Comment by jvendetti** [comment]
Pull request https://github.com/ncbo/bioportal_web_ui/pull/221 has been merged to the master branch
