### ISSUE TITLE
ArgumentError (`render file:` should be given the absolute path to a file. '/ontologies/visualize' was given instead)

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#252]
we are seeing a number of the following errors in the logs:
```log
[f52bf212-c4b9-40da-8c6e-157fc20838d4] ArgumentError (`render file:` should be given the absolute path to a file. '/ontologies/visualize' was given instead):
[f52bf212-c4b9-40da-8c6e-157fc20838d4]
[f52bf212-c4b9-40da-8c6e-157fc20838d4] app/controllers/concepts_controller.rb:35:in `show'
```

**Comment by jvendetti** [comment]
Adding more information since it took me a while to figure out how to reproduce this error in my local dev environment. The URL pattern that triggers the above code is /ajax_concepts/:ontology, and you need to pass a valid class id as part of the query string, e.g.: 

http://localhost:3000/ajax_concepts/BRO?id=http%3A%2F%2Fbioontology.org%2Fontologies%2FActivity.owl%23Activity.

I couldn't find any functionality in the current Rails application that will generate a request with this pattern. Maybe I'm missing something though.

**Comment by syphax-bouazzouni** [comment]
Hi @jvendetti ,
I met with this call while working on this  https://github.com/ncbo/bioportal_web_ui/pull/223

And I think that this is where it is called

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/29259906/215604563-9c9fe1d9-4d78-4016-b14e-94d82a683590.png">

The request parameter for concept id  can be `id` like in your example, but also `conceptid` (see https://github.com/ncbo/bioportal_web_ui/blob/master/app/controllers/concepts_controller.rb#L10)

It is used to get concept/class details in ajax by the ontology_viewer, when you click for a concept in the tree view.

The bug occurs when you try to access that link with a regular call, which will call the no-more-used block (the else block) https://github.com/ncbo/bioportal_web_ui/blob/master/app/controllers/concepts_controller.rb#L35

I hope this help (and that I'm not off topic)

**Comment by jvendetti** [comment]
Thanks for the additional details Syphax. I had assumed there would be a way to manually trigger the else block beginning on [line 26](https://github.com/ncbo/bioportal_web_ui/blob/71891ecdf341c267564ed14610baae707e4d37a5/app/controllers/concepts_controller.rb#L26) from the Rails application.

Our New Relic monitoring software is reporting a large number of errors from this URL pattern that come in as regular calls and trigger the else block. Roughly 7K errors over the last 7 days:

![Screen Shot 2023-01-30 at 3 26 50 PM](https://user-images.githubusercontent.com/1696923/215620219-cc3a7044-2b2d-4391-a357-ec0e80641656.png)
