### ISSUE TITLE
Retire old code for reveiwing ontologies

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#257]
The ability to review (leave a star-based rating) for an ontology was disabled 5 years ago in 2018. The code is still lingering in the code base and should be removed to reduce clutter.

**Comment by syphax-bouazzouni** [comment]
Yeah, code idea.

Just be aware that the review functionality, is still wanted but more in a modern way. You can see this https://github.com/ontoportal/ontoportal-project/issues/10. I think you should remove only the frontend part of this feature. 

Related to this also see https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/69 and https://github.com/ncbo/bioportal_web_ui/issues/219

**Comment by jvendetti** [comment]
Yes, agreed - this only removes review-related code from the Rails application, not the REST API.
