### ISSUE TITLE
UI Admin interface shows error 'JSON::ParserError: unexpected token at' when deleting ontologies

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#260]
I get an error when deleting any ontology using Admin Web interface.  Ontology gets deleted but UI shows "JSON::ParserError: unexpected token at '' error

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1591816/230468433-59574d9f-d2e0-42cb-9e88-ebaae7ba1ea3.png">

**Comment by syphax-bouazzouni** [comment]
We had the same issue https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/226 and fixed it with this PR https://github.com/ncbo/bioportal_web_ui/pull/261

**Comment by alexskr** [comment]
thanks @syphax-bouazzouni, this PR seems to fix this particular issue

**Comment by jvendetti** [comment]
Deployed to production in the [6.10.3](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.10.3) release
