### ISSUE TITLE
Link to UMLS licensing information is broken

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#268]
There are currently 26 ontologies imported from the UMLS that are configured to display the same licensing blurb:

> This ontology is made  available via the UMLS. Users of all UMLS ontologies must abide by the  terms of the UMLS license, available at https://uts.nlm.nih.gov/license.html.

The link to the UMLS license results in a 404.

**Comment by jvendetti** [comment]
@graybeal - it looks like there might be a couple of options for an updated link. One is a landing page of sorts for licensing and accessing UMLS data:

https://www.nlm.nih.gov/databases/umls.html

... and the other is a direct link to the PDF license agreement:

https://uts.nlm.nih.gov/uts/assets/LicenseAgreement.pdf

Which do you prefer?

**Comment by graybeal** [comment]
The second one please. (It will be less confusing for our users. I hope.)

**Comment by jvendetti** [comment]
Fixed by commit https://github.com/ncbo/bioportal_config/commit/b89854430e0a98beae178db82613ff3670d9c7fc
