### ISSUE TITLE
Update _ga_tracking partial with new Google Analytics tag

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#270]
The [_ga_tracking partial](https://github.com/ncbo/bioportal_web_ui/blob/615f5a9f5b0c653c7fb354bb4e99f02e782e76e8/app/views/application/_ga_tracking.html.haml) currently refers to the analytics.js Google Analytics tag that will expire in roughly 28 days. We need to replace it with the newer gtag.js tag:

> In order to experience this new Analytics, you will need to upgrade to Google's latest tagging solution. By updating your current Google Analytics tag (analytics.js) to the Google tag (gtag.js), not only will you have access to the new Analytics, you will also benefit from...

Relates to https://github.com/ncbo/bioportal-project/issues/248

As part of this work, we should start storing the analytics ID in encrypted credentials instead of the `bioportal_config_#{Rails.env}.rb` files.

**Comment by alexskr** [comment]
GA v4 recommends to use gtag.js instead of analytics.js https://support.google.com/analytics/answer/10271001
We should update our ga tracking partial to use gtag.js:

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXX');
</script>
```
where G-XXXXXXX is our gtag ID

**Comment by alexskr** [comment]
I added newly generated GA v4 ID to our private config repo
