### ISSUE TITLE
Add a natural language selector to the ontology submission form

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#311]
Give users the ability to select the language of the content of their ontology when they add or edit ontology submissions. The available options should match the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) standard.

Example options for the select box:

```ruby
['English', 'en'],
['French', 'fr']
```

User selections will be recorded in the [naturalLanguage](https://github.com/ncbo/ontologies_linked_data/blob/4dc3b1123e871b53ba9eb51983ff69c5d2c75c18/lib/ontologies_linked_data/models/ontology_submission.rb#L38) attribute on `OntologySubmission`.

This is a necessary enhancement to accommodate https://github.com/ncbo/bioportal-project/issues/304.

**Comment by jonquet** [comment]
You can see here the restrictions for the naturalLanguage property including URIs (let's think semantic web!) for the values:

https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/config/schemes/ontology_submission.ym

**Comment by jvendetti** [comment]
Hi Clement - I'm aware of AgroPortal's choice to use Lexvo.org URIs for language representation. I broached this topic here at the lab, and also with the team at Berkeley. There was resistance to adopting Lexvo, mainly because others felt that it doesn't naturally align with a variety of standards that use string-based representations, e.g.:

JSON-LD: `"@language": "en"`

RDF: `"Hello World"@en`

SHACL: `sh:languageIn ( "en" )`

ShEX: `ex:name rdf:langString @en ;`

**Comment by jonquet** [comment]
Well.. not exactly. 
Here you're giving me example of syntax to express **that a label is in a given language** (well is actual meaning is "this is the label used in this langage to identify this thing")

On my side, I am talking about **identifying a langage to assign it as a value of a RDF property**. It's not the same. 
Basically we are opposing the following triple: 

ONTO-URI omv:naturalLanguage "en"
with the triple
ONTO-URI omv:naturalLanguage http://lexvo.org/id/iso639-1/en

The latest triple use an URI to identify the langage, which means a machine can use this too: 
- Grab and display the label of the langage in the relevant UI langage: "Anglais" or "English"
- Get a logo  image of the language
- Know that this one is actually the same (owl:sameAs) than http://lexvo.org/id/iso639-3/eng
- etc. 

We are in the semantic web application and the semantic is built out of URIs not conventional ISO standard code. 

You can still counter argue than in [OMV](https://sourceforge.net/projects/omv2/files/OMV%20Core%20Ontology/OMV_v2.4.1.owl/download) omv:naturalLanguage is defined has a DataProperty and not an ObjectProperty indeed. But we have not taken care of the logical coherence of the metadata in BioPortal much (in fact the property you will have to stay consistent with BioPortal shall certainly be metadata:omvnaturallanguage) which at the end is a totally different property from OMV making somekind of reference to OMV. 
In the future , OMV has been "adopted" by MOD and MOD recommend to use [dct:language](http://purl.org/dc/terms/language) which does not define a formal range (only sugegstion with "range includes" )

So I still believe we shall use an URI for as much metadata value as possible (license, ontology types, syntax, representation language) etc.

If you don't like Lexvo, consider the LOC URIs e.g., http://id.loc.gov/vocabulary/iso639-1/en

**Comment by jvendetti** [comment]
@cmungall @matthewhorridge @martinjoconnor

Would any of you care to comment on the topic of whether to represent ontology language content in BioPortal as Lexo URIs vs two-letter ISO 639-1 strings?

Should this be a separate issue in another location?

I'm trying my best to be accommodating, while at the same time moving BioPortal forward on this without a lot of delay.
