### ISSUE TITLE
Bundle install fails on Apple M2 for the iconv gem

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#320]
I'm attempting to set up a local development environment on a newer MacBook Pro with an Apple M2 Max chip, and macOS Sonoma 14.5. Running the `bundle install` command for the master branch fails with:

```c
iconv.c:709:50: error: incompatible function pointer types passing 'VALUE (VALUE, VALUE)' (aka 'unsigned long (unsigned long, unsigned long)') to parameter of type
'rb_block_call_func_t' (aka 'unsigned long (*)(unsigned long, unsigned long, int, const unsigned long *, unsigned long)') [-Wincompatible-function-pointer-types]
        rb_block_call(options, rb_intern("each"), 0, 0, get_iconv_opt_i, (VALUE)opt);
                                                        ^~~~~~~~~~~~~~~
```

I've run some local searches of the codebase, and it's not evident that we use the [iconv gem](https://github.com/ruby/iconv) anymore. That being said, I suggest removing it as a dependency.

**Comment by syphax-bouazzouni** [comment]
Just for information, we removed Iconv gem in our code base, as it was not used.
