### ISSUE TITLE
Page Title are set incorrectly when browsing class tree

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#358]
<img width="890" alt="image" src="https://github.com/user-attachments/assets/aeb233b8-44ae-42fa-8859-1da6e0aa45a6">

**Comment by mdorf** [comment]
This is fixed in https://github.com/ncbo/bioportal_web_ui/commit/59b4b1ab3c6fd81833370802b7a2fcc5f41cf049
