### ISSUE TITLE
NCBO BioPortal Appliance AMI

### ISSUE THREAD

**Issue by gibiceh** [ncbo/bioportal_web_ui#42]
I apologize if this is the wrong forum for this question.  If this is the wrong forum, I would appreciate any assistance in pointing me to the correct support forum.

I recently installed version 2.4 of the NCBO BioPortal Appliance AMI on a m3.large aws ec2 instance.  After uploading an ontology via an OWL file, I noticed that "Loading" messages would persist when accessing the Classes and Properties tabs of the ontology.  This behavior was seen for both the standard default ontology packaged with the AMI and the ontology that I supplied.  It would take a page refresh in order to load the content of these tabs.  Is it known how to remedy this behavior.

In addition, I noticed that version 2.3 of the appliciance was available as an AMI on aws.  I installed this version on the same instance type and was successfully able to access the Classes tab for both my provided ontology and the pre-packaged ontology that came with the appliance.  However I did not see where Properties could be viewed.  Are Properties unable to be viewed in version 2.3, or is there a setting that needs to be enabled in order to view them.

Thank you so much for any help provided and please let me know if any further information would help answer my inquiry.

**Comment by jvendetti** [comment]
@graybeal : moved this issue to the appropriate repository ([issue #15](https://github.com/ncbo/bioportal-project/issues/15)).
