### ISSUE TITLE
Error when submitting "Summary Only" ontologies

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal_web_ui#47]
When someone submit a new ontology with the option “Metadata Only”, and fill all the information required, there is a message “something went wrong” after clicking on Add Submission.

**Comment by jvendetti** [comment]
This was fixed by code gleaned from a pull request (https://github.com/ncbo/bioportal_web_ui/pull/8,  from @vemonet), and also by one additional commit to fix a template double render error (https://github.com/ncbo/bioportal_web_ui/commit/96a5000148049384df6c360305289e3dade4fcbc).
