### ISSUE TITLE
jquery.autocomplete.css loads from hardcoded URL

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#54]
stage.biootnology.org makes users load .js and .css scripts from bioportal.bioontology.org instead of from stage.bioontology.org. This is the case for NCBO Appliance as well.
http://bioportal.bioontology.org/javascripts/JqueryPlugins/autocomplete/jquery.autocomplete.css
http://bioportal.bioontology.org/javascripts/bp_crossdomain_autocomplete.js?_=1446073964103

setting BP_INTERNAL_SEARCH_SERVER variable in ioportal_config_env.rb doesn't do the trick

**Comment by jvendetti** [comment]
Just for clarification, BP_INTERNAL_SEARCH_SERVER is hard-coded to point to production in [this line of code](https://github.com/ncbo/bioportal_web_ui/blob/master/app/assets/javascripts/bp_form_complete.js#L8) in bp_form_complete.js.
