### ISSUE TITLE
Validate user entry of URI in the OWL properties

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#57]
URI do not get encoded properly (or validated) when users edit OWL ontology properties.  
For example, users mistakenly put their names instead of URI into preferred name property.  This data gets saved into triple store in the following manner:

``<http://data.bioontology.org/ontologies/ACRONYM/submissions/1> <http://data.bioontology.org/metadata/authorProperty> <local:Firstname\u0020\Lastname> .
``
``
<http://data.bioontology.org/ontologies/ACRONYM/submissions/5> <http://data.bioontology.org/metadata/prefLabelProperty> <local:My Ontology Name> .
``

This creates problems for us when metadata graph is imported back into the triple store:

``URI http://data.bioontology.org/metadata/OntologySubmission:8009 raptor error - Turtle URI error - illegal Unicode escape \u0020 in URI.``

**Comment by alexskr** [comment]
API and/or UI need to validate the user's input to make sure a valid URI is entered for those fields.   
Users seem to be confused about this over a number of years so this submission form should benefit from a clear instruction that entries have to be in the URI format

**Comment by alexskr** [comment]
fixed by https://github.com/ncbo/goo/pull/138 and https://github.com/ncbo/goo/pull/139

![image](https://github.com/ncbo/bioportal_web_ui/assets/1591816/b97ff7ef-e2d3-4694-adce-2a49c08fb997)

**Comment by syphax-bouazzouni** [comment]
Always great to see, old issues being closed.
The error display, is fixed locally in our new UI (see https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/320). But will take us some time to do a PR for you. 
But a temporary solution can be by updating these lines https://github.com/ncbo/bioportal_web_ui/blob/master/app/views/submissions/_form.html.haml#L3-L8 like so  https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/master/app/views/submissions/_form.html.haml#L22-L31

**Comment by alexskr** [comment]
@syphax-bouazzouni Thanks for the tip!

**Comment by alexskr** [comment]
looks much better
![image](https://github.com/ncbo/bioportal_web_ui/assets/1591816/684ac107-4a01-46c0-8cef-461e610dd4d9)
