### ISSUE TITLE
Annotator does not return any results

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal_web_ui#61]
The REST services work fine:

http://data.bioontology.org/annotator?text=Melanoma%20is%20a%20malignant%20tumor%20of%20melanocytes%20which%20are%20found%20predominantly%20in%20skin%20but%20also%20in%20the%20bowel%20and%20the%20eye.&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false

The Annotator UI shows "No annotations found"

**Comment by mdorf** [comment]
At the moment, it appears that the REST service call returns no results because of the presence of `&include=prefLabel` parameter in the call. Continuing to investigate...

http://data.bioontology.org/annotator?text=Melanoma%20is%20a%20malignant%20tumor%20of%20melanocytes%20which%20are%20found%20predominantly%20in%20skin%20but%20also%20in%20the%20bowel%20and%20the%20eye.&longest_only=false&exclude_numbers=false&whole_word_only=false&exclude_synonyms=false&include=prefLabel

**Comment by jvendetti** [comment]
This behavior doesn't seem specific to the ```include=prefLabel``` parameter. I tested calls with other include parameters and they all return an empty set in production, e.g.:

```
http://data.bioontology.org/annotator?text=Melanoma&include=cui
http://data.bioontology.org/annotator?text=Melanoma&include=definition
http://data.bioontology.org/annotator?text=Melanoma&include=synonym
```

Unable to reproduce this behavior in my local dev environment.

**Comment by jvendetti** [comment]
I looked at the REST logs on ncboprod-rest1. The calls to the annotator endpoint are returning 200 status, e.g.:

```
172.20.222.51 - ncbobioportal [16/Aug/2017:06:13:42 -0700] "GET /annotator?text=Underdosing+of+stimulant+laxatives%2C+subsequent+encounter&include=prefLabel&ontologies=ICD10CM&longest_only=false&recognizer=&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false HTTP/1.0" 200 2 1.0235
```

In my local dev environment, the above call returns data (vs. production, which returns an empty set).

**Comment by mdorf** [comment]
I believe I understand the root of the issue. It also explains why we are unable to reproduce this in our local environment. Somehow, my Solr schema changes that were supposed to be released to Staging, also ended up in Production. These schema changes are accompanied by the code changes which are active in our development environment but have not yet made it to production. The problem should be fixed by reverting the Solr schema to its original production version.

**Comment by mdorf** [comment]
Solr schema reverted. Issue fixed.
