### ISSUE TITLE
Various problems with display of Disease Ontology

### ISSUE THREAD

**Issue by cmungall** [ncbo/bioportal_web_ui#62]
See this screenshot:

![image](https://user-images.githubusercontent.com/50745/29472066-54718734-8407-11e7-86af-23f1d4bc808b.png)

 * The arrows are pointing in the wrong direction
 * There is a missing entry. It shows up as blank in tree view and `<no pref label>` in graph view
 * the ancestry is incomplete. Compare with OLS which also shows parentage to melanoma: http://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_1108

**Comment by jvendetti** [comment]
The second bullet point from above is fixed (blank node in tree view and `<no pref label>` in the path to root visualization).

![screenshot 2017-08-23 17 02 31](https://user-images.githubusercontent.com/1696923/29643636-2e0df952-8825-11e7-88b6-67dec9cda5f7.png)

**Comment by jvendetti** [comment]
@cmungall: this comment is in regard to your last bullet point about the incomplete ancestry. I looked into this and noticed that BioPortal and the OLS are using different versions of the disease ontology. BioPortal is currently configured to pull new versions from this GitHub URL:

https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid-non-classified.obo

The OBO file that we pull from that location is in contrast to the OWL version of the ontology that OLS is using. They download from a different URL: 

https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.owl

I opened both ontologies in Protege and can see that the OWL version that OLS uses has additional equivalent to axioms that account for the display of "esophagus melanoma" at multiple places in the hierarchy.

Is it your opinion that BioPortal should be configured to download the OWL version of the disease ontology from the same location that's specified by OLS? In BioPortal, the only contact person listed for the disease ontology is currently someone named Lynn Schriml. I can make this update if you think it's appropriate.

**Comment by cmungall** [comment]
My own personal view is that OLS, BioPortal, Ontobee should all show the same thing, and the doid.owl should be canonical. However, you should consult with Lynn since she is the DO contact.

**Comment by jvendetti** [comment]
Thanks for the feedback. I'll contact Lynn and ask her if she'd be OK with us pulling doid.owl.

**Comment by jvendetti** [comment]
Consulted with Lynn, who indicated a preference to keep the OBO version of DOID in BioPortal. Seems the conclusion is that the display differences between OLS and BioPortal will persist.

Moved the remaining item about display arrows pointing in the wrong direction to the [BioMixer repository](https://github.com/ncbo/biomixer/issues/4).
