### ISSUE TITLE
New account creation fails for email addresses with long top-level domains

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#66]
The form that allows new users to register for a BioPortal account:

https://bioportal.bioontology.org/accounts/new

... fails if the user's email address has a top-level domain longer than 4 characters, e.g., ".swiss".

**Comment by graybeal** [comment]
I suspect the test should be explicitly "does this domain exist?" either that or send them a confirmation email...

**Comment by graybeal** [comment]
removing the restriction is ok too
