### ISSUE TITLE
Visualization option on the mappings page is broken

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal_web_ui#73]
1. Go to: http://bioportal.bioontology.org/mappings
2. Select an ontology
3. Choose the "Visualization" radio button option.
Nothing appears on the page. There is a javascript error:

TypeError: this.zoom is undefined.

Reported by @jonquet (Clement).

**Comment by jvendetti** [comment]
This is a duplicate of https://github.com/ncbo/biomixer/issues/3. Visualizations in BioPortal are provided by 3rd party software (Biomixer), which is a different code base / repository.
