### ISSUE TITLE
Jump To and Form Autocomplete widget demonstrations are broken

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#79]
Navigate to the Widgets page for any ontology, e.g.: 

https://bioportal.bioontology.org/ontologies/BRO/?p=widgets.

### Jump To

Enter any class name in the "Jump To" widget demonstration and notice that clicking on the "Go to BioPortal" button does nothing. The console window contains the following JS error:

```
Uncaught TypeError: Cannot read property 'findValue' of undefined
```

... thrown at [this line](https://github.com/ncbo/bioportal_web_ui/blob/master/public/javascripts/widgets/quick_jump.js#L275) in quick_jump.js.

### Form Autocomplete

Entering a class name in any of the "Example 1", "Example 2", or "Example 3" widget demonstration text boxes does nothing. No errors in the console. Intended widget functionality is [described on the NCBO wiki](https://www.bioontology.org/wiki/NCBO_Widgets#Term-selection_field_on_a_form). Code is located in [form_complete.js](https://github.com/ncbo/bioportal_web_ui/blob/master/public/javascripts/widgets/form_complete.js).

**Comment by graybeal** [comment]
Got an email on the support list about this today (below). Additional notes: The visualization only works if http; in the one test I did, the search for class widget (at the bottom of the page) worked only in https. The top widgets didn't work in either http or https.

```
Example 2: http://bioportal.bioontology.org/ontologies/MEDDRA?p=widgets 
When I clicked on Widget type Jumpt to get code notting happens.
```

**Comment by graybeal** [comment]
A user writes: 

> Hi, I'm trying to implement the NCBO web widget form autocomplete for a company's project. I follow the directions on the wiki but ran this error in the javascript console.
> 
> jQuery(...).bioportal_autocomplete is not a function.
> 
> I went on the form_complete.js code and found on line 273 that it seems I have to include a script that I assumed you guys had called public/javascripts/JqueryPlugins/autocomplete/crossdomain_autocomplete.js 
> I was wondering if this script was suppose to be included with the form_complete.js and if so I was wondering how I can access it?

**Comment by jvendetti** [comment]
Fixed by https://github.com/ncbo/bioportal_web_ui/pull/242
