### ISSUE TITLE
Integrate AnnotatorPlus UI

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#83]
The [SIFR project](https://github.com/sifrproject) developed and deployed an enhanced version of BioPortal's Annotator that offers negation, additional output formats, etc. See their UI and proxy code here:

https://github.com/sifrproject/bioportal_web_ui
https://github.com/sifrproject/annotators

Mark would like us to integrate "AnnotatorPlus" into BioPortal, offering it alongside our current Annotator. 

We received a patch file from Andon (@twktheainur) created from our staging branch on Nov. 16, 2017 (HEAD at d6a68fba0fa11cdd3b1bb4d6bcee50d0746047ed), which should give us a starting point for the integration.

**Comment by jonquet** [comment]
As a quick update, this is described briefly here: https://dx.doi.org/10.1093/bioinformatics/bty009
For convenience I am adding here an example: 
**using AnnotatorPlus in NCBO BioPortal
http://services.data.bioontology.org/annotatorplus/?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb&text=The%2520patient%2520has%2520no%2520sign%2520of%2520melanoma,%2520but%2520his%2520father%2520had%2520history%2520of%2520skin%2520cancer&longest_only=false&exclude_numbers=false&whole_word_only=false&exclude_synonyms=false&negation=true&experiencer=true&temporality=true&score_threshold=0&confidence_threshold=0&semantic_groups=DISO

**using AnnotatorPlus in SIFR BioPortal
http://services.bioportal.lirmm.fr/ncbo_annotatorplus/?text=The%20patient%20has%20no%20sign%20of%20melanoma,%20but%20his%20father%20had%20history%20of%20skin%20cancer&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false&negation=true&experiencer=true&temporality=true&score_threshold=0&confidence_threshold=0&lemmatize=false&score=cvalue&semantic_groups=DISO&display_links=false&display_context=false&apikey=4a5011ea-75fa-4be6-8e89-f45c8c84844e

Results seems too be the same.

@twktheainur is working on updating the "annotators" proxy code to adopt the latest branch for the NegEx/ConText component. We have some work to do for French, but shall be ok for English. 
Changes shall be trivial to merge.

**Comment by jvendetti** [comment]
The patch from @twktheainur was integrated in this commit: https://github.com/ncbo/bioportal_web_ui/commit/0207d42898c203e0d776fba614ff4b0c14160dad.
