### ISSUE TITLE
current load of Bioassay Ontology is not the reasoned version -> Have an Ontology Metadata annotation to indicate that fact

### ISSUE THREAD

**Issue by proccaserra** [ncbo/bioportal_web_ui#99]
@graybeal 

information-artifact-ontology/ontology-metadata#41 (comment)

Case in point: OLS and BIoportal serve different versions of the same resource (which is not OBO foundry, but the same situation could affect any of OBO ontology.

 it seems that NCBO Bioportal loaded the unreasoned version -> only asserted classes: (BAO pulled from github repo https://raw.githubusercontent.com/BioAssayOntology/BAO/master/bao_complete_merged.owl
(because the following owl file http://www.bioassayontology.org/bao/bao_complete.owl served by OLS and Bioportal does not load in Protege)
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/517736/59835992-a4971480-9342-11e9-80ea-1712e0f818cd.png">

Getting the inferred hierarchy (running hermit reasoner in Protege) shows the following:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/517736/59836217-08b9d880-9343-11e9-8d7d-1429ead7ea80.png">

Pay attention to the Protege view Inferred / Asserted toggle box.

OLS is loading the complete-merge & reasoned version of BAO
NCBO seems to be loaded the asserted version.

this would be my explanation to the difference you observed.

**Comment by jvendetti** [comment]
@proccaserra - I looked at the how BAO is configured in BioPortal. It was set up to pull new versions from this URL:

http://www.bioassayontology.org/bao/bao_complete.owl

I assume this is the location of the "asserted" version that you mention above? Is the desire to instead load from this URL:

https://raw.githubusercontent.com/BioAssayOntology/BAO/master/bao_complete_merged.owl

? If so, we can make that change. On a related note, the contact for this ontology in our system is "Stephan Schurer, sschurer@med.miami.edu". Is this current/correct?

**Comment by proccaserra** [comment]
@jvendetti, indeed Stephan Schurer is the owner of BAO. I reported the issue (which is not really related to 'BioPortal_web_ui' component but I could not find a better place to log this) as a collaborator of mine noticed the difference in rendering between BioPortal and EBI's OLS.
I  assumed that both vocabulary servers would load a reasoned version, which is obviously an incorrect assumption. The ontology owner should indeed clarify that step. best.

**Comment by jvendetti** [comment]
@proccaserra - I checked with Stephan about which version of BAO he wants in BioPortal. He confirmed that he'd like us to continue serving the asserted version (bao_complete.owl). Here is the full text of his response:

> Please keep the bao_complete version. It will automatically connect to all the other bao vocabulary and axiom module files in Protege (via direct and indirect import). The bao_complete_merged is a single files with all these imports, so ultimately these should be the same if it is the same version. It would make more sense for EBI to also serve the bao_complete file.

If you have further follow-up questions / comments, I think it would be best to move this discussion to our user support list (bioontology-support@lists.stanford.edu).
